import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import meRouter from "./me";
import coursesRouter from "./courses";
import assignmentsRouter from "./assignments";
import submissionsRouter from "./submissions";
import quizzesRouter from "./quizzes";
import materialsRouter from "./materials";
import messagingRouter from "./messaging";
import dashboardRouter from "./dashboard";
import gradesRouter from "./grades";
import sessionsRouter from "./sessions";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import cohortsRouter from "./cohorts";
import oversightRouter from "./oversight";
import feedbackRouter from "./feedback";
import groupsRouter from "./groups";
import journalRouter from "./journal";
import invitesRouter from "./invites";
import planRouter from "./plan";
import attendanceRouter from "./attendance";
import courseFeedbackRouter from "./courseFeedback";
import analyticsRouter from "./analytics";
import gradebookRouter from "./gradebook";
import rubricsRouter from "./rubrics";
import announcementsRouter from "./announcements";
import earlyAlertsRouter from "./earlyAlerts";
import discussionsRouter from "./discussions";
import transcriptRouter from "./transcript";
import studentPlanRouter from "./studentPlan";
import studentNotesRouter from "./studentNotes";
import memberGradesRouter from "./memberGrades";
import privacyRouter from "./privacy";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(meRouter);
router.use(coursesRouter);
router.use(assignmentsRouter);
router.use(submissionsRouter);
router.use(quizzesRouter);
router.use(materialsRouter);
router.use(messagingRouter);
router.use(dashboardRouter);
router.use(gradesRouter);
router.use(sessionsRouter);
router.use(notificationsRouter);
router.use(adminRouter);
router.use(cohortsRouter);
router.use(oversightRouter);
router.use(feedbackRouter);
router.use(groupsRouter);
router.use(journalRouter);
router.use(invitesRouter);
router.use(planRouter);
router.use(attendanceRouter);
router.use(courseFeedbackRouter);
router.use(analyticsRouter);
router.use(gradebookRouter);
router.use(rubricsRouter);
router.use(announcementsRouter);
router.use(earlyAlertsRouter);
router.use(discussionsRouter);
router.use(transcriptRouter);
router.use(studentPlanRouter);
router.use(studentNotesRouter);
router.use(memberGradesRouter);
router.use(privacyRouter);

export default router;
